### ISSUE TITLE
flatpak build: something depends on gtk4 >= 4.5 but runtime contains 4.4.1

### ISSUE THREAD

**Issue by znalo** [timlau/adw_pydemo#1]
not sure what the dependency comes from or where to look for this, but will burrow into the files to possibly find out.

**Comment by znalo** [comment]
edited to say (gnome) runtime (flatpak) has gtk 4.4.1, not 4.1.4.

**Comment by znalo** [comment]
ok - turns out it is libadwaita (now at 1.0 and a bit) that requires gtk>=4.5, so the remedy is to use gnome nightly flatpak for the Runtime and SDK.  [remedy to be confirmed].  At some stage README flatpak recipe could say /42 when it is released.

**Comment by znalo** [comment]
flatpak builds and runs after installing org.gnome.Platform//master and org.gnome.SDK//master from gnome-nightly flatpak repo and specifying 'runtime-version: "master"' (instead of "41") in dk.rasmil.AdwPyDemo.yml.

**Comment by timlau** [comment]
Please make a PR to the updated .yml file and i will add it.
The flatpak builds libadwaita from upstream git repo and it can have updated its requirement to something not in the gnome platform 41.

**Comment by znalo** [comment]
Great! Thanks :-)
